#!/usr/bin/env python3

"""
Download the historical and predicitions data.
"""

from argparse import ArgumentParser, RawDescriptionHelpFormatter

from sportsbet.soccer.data import LEAGUES_MAPPING, download_data


def fetch_data():
    
    # Create parser description
    description = 'Select the leagues parameter from the following leagues:\n\n'
    for league_id, league_name in LEAGUES_MAPPING.items():
        description += '{} ({})\n'.format(league_id, league_name)

    # Create parser
    parser = ArgumentParser(description=description, formatter_class=RawDescriptionHelpFormatter)

    # Add arguments
    parser.add_argument('leagues', nargs='*', default=['all'], help='One of all or any league ids from above.')
    
    # Parse arguments
    args = parser.parse_args()

    # Adjust parameter
    leagues = args.leagues
    if len(leagues) == 1 and leagues[0] == 'all':
        leagues = leagues[0]

    # Fetch data
    try:
        download_data(leagues=leagues, data_type='historical')
    except Exception:
        print('Failed to download historical data.')
    try:
        download_data(leagues=leagues, data_type='predictions')
    except Exception:
        print('Failed to download predictions data.')


if __name__ == '__main__':
    fetch_data()
