#!/usr/bin/env python3

"""
Update the training data.
"""

from argparse import ArgumentParser, RawDescriptionHelpFormatter

from sportsbet.soccer.data import LEAGUES_MAPPING
from sportsbet.soccer import BettingAgent


def fetch_training_data():
    
    # Parse the leagues parameter
    description = 'Parse the leagues parameter from the following leagues:\n\n'
    for league_name, (league_id, _) in LEAGUES_MAPPING.items():
        description += '{} ({})\n'.format(league_id, league_name)
    parser = ArgumentParser(description=description, formatter_class=RawDescriptionHelpFormatter)
    help_msg = 'One of all, main or any league ids from above.'
    parser.add_argument('leagues', nargs='*', default=['all'], help=help_msg)
    args = parser.parse_args()

    # Create betting agent
    betting_agent = BettingAgent()

    # Fetch training data
    leagues = args.leagues
    if len(leagues) == 1 and leagues[0] in ('all', 'main'):
        leagues = leagues[0]
    betting_agent.fetch_training_data(leagues=leagues)


if __name__ == '__main__':
    fetch_training_data()
