#!/usr/bin/env python3

"""
Predict using a selected classifier.
"""

from os.path import join
from argparse import ArgumentParser

from sportsbet.soccer.optimization import RESULTS_PATH
from sportsbet.soccer import BettingAgent
from sportsbet.soccer.utils import CLASSIFIERS


def parse_args():
    """Parse command line arguments."""
    
    # Create parser
    parser = ArgumentParser('Predict using a selected classifier.')
    
    # Add arguments
    parser.add_argument('--backtest-index', default=0, help='The index of the backtesting result.')
      
    return parser.parse_args()


if __name__ == '__main__':
    
    # Parse arguments
    args = vars(parse_args())
    
    # Create betting agent
    betting_agent = BettingAgent()

    # Generate predictions
    predictions = betting_agent.predict(args['backtest_index'])

    # Save predictinos
    predictions.to_csv(join(RESULTS_PATH, args['backtest_index'], 'predictions.csv'), index=False)

    
