#!/usr/bin/env python3

"""
Train a selected classifier.
"""

from argparse import ArgumentParser

from sportsbet.soccer import BettingAgent


def parse_args():
    """Parse command line arguments."""
    
    # Create parser
    parser = ArgumentParser('Train a selected classifier.')
    
    # Add arguments
    parser.add_argument('--backtest-index', default=0, help='The index of the backtesting result.')
    
    return parser.parse_args()
    

if __name__ == '__main__':
    
    # Parse arguments
    args = vars(parse_args())
    
    # Create betting agent
    betting_agent = BettingAgent()

    # Fit and dump classifier
    betting_agent.fit_dump_classifiers(args['backtest_index'])
