repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.10
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        exclude: ^(docs/examples/|docs/generated/|tests/fixtures)
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, tests, chore]
-   repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: pdm tests
        pass_filenames: false
        language: system
        types: [python]
