repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: ruff
        name: Lint with the project's ruff
        entry: pdm run ruff check --fix
        language: system
        types: [python]
      - id: black
        name: Format with the project's black
        entry: pdm run black
        language: system
        types: [python]
        exclude: ^(docs/examples/|docs/generated/|tests/fixtures)
      - id: mypy-src
        name: Type check src with the project's mypy
        entry: pdm run mypy src
        pass_filenames: false
        language: system
        types: [python]
      - id: mypy-tests
        name: Type check tests with the project's mypy
        entry: pdm run mypy tests
        pass_filenames: false
        language: system
        types: [python]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, tests, chore]
-   repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: 'pdm tests'
        pass_filenames: false
        language: system
        types: [python]
