name: Bug report
description: Create a report to help us reproduce and correct the bug.
labels: ['fix']

body:
- type: markdown
  attributes:
    value: >
      **Before submitting a bug, please make sure the issue hasn't been already addressed by searching
      through [the past issues](https://github.com/georgedouzas/sports-betting/issues).**
- type: textarea
  attributes:
    label: Describe the bug
    description: >
      A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps or code to reproduce the bug
    description: |
      Please add a minimal code example that can reproduce the error when running it.
      If the code is too long, feel free to put it in a public gist and link it in the issue.
    placeholder: |
      ```
      Sample code to reproduce the problem
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Results
    description: >
      Please paste or describe the expected results.
    placeholder: >
      Example: No error is thrown.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Results
    description: |
      Please paste or describe the results you observe instead of the expected results. If you observe an error, please paste
      the error message including the **full traceback** of the exception.
    placeholder: >
      Please paste or specifically describe the actual output or traceback.
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Please provide the following information.
    placeholder: >
      `sports-betting` version
      Python version
      OS
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing!
