name: Feature request
description: Suggest a new algorithm, enhancement to an existing algorithm, etc.
labels: ['feat']

body:
- type: textarea
  attributes:
    label: Describe the new feature you propose to be implemented
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your proposed solution
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you have considered, if relevant
- type: textarea
  attributes:
    label: Additional context
