package:
  name: sports-betting
  version: "0.1.3"

source:
  url: "https://files.pythonhosted.org/packages/d9/1a/4b1270b902b997a4592cad0ae7216cb7672e1cc9805e961d48938e9a042e/sports-betting-0.1.3.tar.gz"
  sha256: "a1d64872818156357cff05e956e9981caa97349cc682537b180ccd50dfc3b916"

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python
    - pandas >=1.0.0
    - scikit-learn >=1.0.0
    - cloudpickle >=2.0.0
    - beautifulsoup4 >=4.0.0
    - rich >=4.28

  run:
    - python
    - pandas >=1.0.0
    - scikit-learn >=1.0.0
    - cloudpickle >=2.0.0
    - beautifulsoup4 >=4.0.0
    - rich >=4.28

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - sportsbet

about:
  home: "https://github.com/georgedouzas/sports-betting"
  license: "MIT"
  license_file: ""
