name: CI

on:
  push:
    branches:
      - main

jobs:

  checks:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python versions
      uses: actions/setup-python@v4
      with:
        python-version: |
            3.9
            3.10
            
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        cache: true
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: pdm install --no-default -dG maintenance -dG checks

    - name: Check code quality
      run: pdm checks quality

    - name: Check type annotations
      run: pdm checks types

    - name: Check vulnerabilities in dependencies
      run: pdm checks dependencies

  tests:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python versions
      uses: actions/setup-python@v4
      with:
        python-version: |
            3.9
            3.10
            
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        cache: true
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: pdm install -dG maintenance -dG tests

    - name: Run the test suite
      run: pdm tests
