name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        cache: true
        cache-dependency-path: pyproject.toml

    - name: Build distribution
      run: pdm build

    - name: Upload distribution artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  github-release:

    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download distribution artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true

  pypi-release:

    needs: build

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/sports-betting

    permissions:
      id-token: write

    steps:
    - name: Download distribution artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
